name = "vinh-dev"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-11"

[placement]
mode = "smart"

[vars]
BUN_VERSION = "1.2.1"
NODE_VERSION = "22.13.1"

[env.production.vars]
BUN_VERSION = "1.2.1"
NODE_VERSION = "22.13.1"
